config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  root to: 'pages#home'
  resources :movies, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director

  searchkick
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title, :syllabus]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:query].present?
      @movies = Movie.global_search(params[:query])
    else
      @movies = Movie.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbSearch488Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <%= form_tag movies_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control mb-3",
          placeholder: "Find a movie"
        %>
      <% end %>

      <div id="movies">
        <% @movies.each do |movie| %>
          <h4><%= movie.title %></h4>
          <p><%= movie.syllabus %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container text-center mt-5">
	<%= link_to "Browse Movies", movies_path, class: "btn btn-dark" %>
</div>